Traceback (most recent call last):
  File "/work/nikki/MT/code/service.py", line 41, in <module>
    read_file()
  File "/work/nikki/MT/code/service.py", line 32, in read_file
    filtered_df = df[['Question', 'label']]
                  ~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/nikki/miniconda/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/nikki/miniconda/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/work/nikki/miniconda/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Question', 'label'], dtype='object')] are in the [columns]"
srun: error: g001: task 0: Exited with exit code 1
